/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch / Material 3 Civic Sans Design System
        "on-background": "#131b2e",
        "secondary-fixed-dim": "#ffb77d",
        "on-error-container": "#93000a",
        "surface-container": "#eaedff",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffdcc3",
        "primary-fixed-dim": "#99d2be",
        "surface-container-low": "#f2f3ff",
        "outline-variant": "#bfc9c3",
        "on-primary": "#ffffff",
        "surface-container-high": "#e2e7ff",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#86beab",
        "on-primary-fixed-variant": "#155041",
        "on-secondary-fixed-variant": "#6e3900",
        "tertiary-container": "#004971",
        "on-error": "#ffffff",
        "tertiary-fixed": "#cce5ff",
        "secondary": "#904d00",
        "surface-tint": "#316858",
        "on-surface-variant": "#404945",
        "surface-bright": "#faf8ff",
        "primary-fixed": "#b5efda",
        "secondary-container": "#fe932c",
        "inverse-primary": "#99d2be",
        "tertiary": "#00324f",
        "on-secondary-container": "#663500",
        "surface": "#faf8ff",
        "inverse-surface": "#283044",
        "background": "#faf8ff",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#93ccff",
        "primary-container": "#134e3f",
        "outline": "#707975",
        "primary": "#00362a",
        "inverse-on-surface": "#eef0ff",
        "on-surface": "#131b2e",
        "on-primary-fixed": "#002018",
        "surface-container-highest": "#dae2fd",
        "on-tertiary-container": "#60baff",
        "on-tertiary-fixed-variant": "#004b73",
        "surface-variant": "#dae2fd",
        "on-tertiary-fixed": "#001d31",
        "on-secondary-fixed": "#2f1500",
        "surface-dim": "#d2d9f4",

        // Screen-specific legacy brand colors from Stitch prototypes
        brand: {
          50: '#f0fdf4',
          100: '#dcfce7',
          600: '#15803d',
          700: '#166534',
          800: '#14532d',
          900: '#0d381e',
          deep: '#0f4d36',
          navy: '#0b2046',
          green: '#0b5d44',
          forest: '#114a3b',
          forestHover: '#0d3b2f',
          mint: '#eaf4ee',
          darkGreen: '#1b5e40',
          accentGreen: '#107c41',
          lightMint: '#eaf8f0',
          subtleBg: '#f6f8fa',
          textMuted: '#627282',
        },
        app: {
          bg: '#F9FAFB',
          navy: '#0F2942',
          forest: '#114B3F',
          forestLight: '#186354',
          mint: '#EBF7EE',
          mintBorder: '#D2F0DA',
          badgeGreen: '#DCFCE7',
          badgeText: '#15803D',
          subtext: '#64748B',
          chipBorder: '#E2E8F0',
          chipBlue: '#2563EB',
          chipBg: '#FFFFFF',
        },
        sahayak: {
          cream: '#f9f8f3',
          darkGreen: '#1b4332',
          forest: '#2d6a4f',
          accentOrange: '#f77f00',
          badgeBg: '#f2f6f4',
          softGray: '#e2e8f0',
          tagline: '#2d4a3e',
        },
        forest: {
          DEFAULT: '#14533D',
          dark: '#0e3a2b',
          light: '#2d6a4f',
          800: '#144136',
          900: '#0F382E',
        },
        amberSoft: '#fffbeb',
        amberBorder: '#fde68a',
        navytext: '#0C2038',
      },
      fontFamily: {
        sans: ['"Noto Sans Devanagari"', '"Plus Jakarta Sans"', 'Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        caveat: ['Caveat', 'cursive', 'Georgia', 'serif'],
      },
    },
  },
  plugins: [],
};
